🟣 Level 5 — JOIN Practice
--Display order ID, customer name, and order date.
select od.order_ID, cu.customer_name,od.order_date
from customers cu join orders od
on cu.customer_id=od.customer_id
group by 1,2,3
order by cu.customer_name

--Display customer name, city, order ID, and order status.
select cu.customer_name,cu.city, od.order_ID, od.status
from customers cu join orders od
on cu.customer_id=od.customer_id
group by 1,2,3,4
order by cu.customer_name;

--Display product name, quantity, and line total for every order item.
select oi.order_item_id, pr.product_name, oi.quantity, oi.line_total
from products pr join order_items oi
on pr.product_id=oi.product_id
group by 1,2;

--Display customer name and total amount spent.
select cu.customer_name, sum(line_total)total_amount_spent 
from customers cu join orders od
on cu.customer_id=od.customer_id
join order_items oi
on oi.order_id=od.order_id
group by 1;

--Find the total sales generated by each customer.
select cu.customer_name, sum(line_total)total_generated_amount
from customers cu join orders od
on cu.customer_id=od.customer_id
join order_items oi
on oi.order_id=od.order_id
group by 1;

--Find the total quantity purchased by each customer.
select cu.customer_name, sum(oi.quantity)Total_Quantity
from customers cu join orders od
on cu.customer_id=od.customer_id
join order_items oi
on oi.order_id=od.order_id
group by 1;

--Display order ID, customer name, product name, quantity, and line total.
select cu.customer_name,oi.order_ID, pr.product_name,oi.quantity, oi.line_total
from customers cu join orders od
on cu.customer_id=od.customer_id
join order_items oi
on oi.order_id=od.order_id
join products pr
on pr.product_id=oi.product_id
group by 1,2,3,4,5
order by 1

--Find customers who have placed at least one order.
select cu.customer_name,count(*) Order_count from customers cu join orders od
on cu.customer_id=od.customer_id
where od.status='Completed'
group by 1
having count(*)>1 ;

--Find customers who have never placed an order.
select cu.customer_name from 
customers cu left join orders od
on cu.customer_id=od.customer_id
where od.order_id is null;

--Find products that have never been ordered.
select pr.product_id,pr.product_name from 
products pr left join order_items oi
on pr.product_id=oi.product_id
where oi.order_id is null;